# https://blog.csdn.net/CQccccqqq/article/details/144138610
name: Go
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
 
      # 设置 Go 环境
      - name: 设置 Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'
 
      # 构建项目，启用静态编译以确保在 CentOS 上运行
      - name: 构建
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o youappname -ldflags="-s -w" .
 

 
