# https://blog.csdn.net/CQccccqqq/article/details/144138610
name: Go
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  build-2:
    name: 测试部署
    runs-on: ubuntu-latest
    container:
      image: registry.cn-zhangjiakou.aliyuncs.com/matrix-net/docker:26.1.4-dind-alpine3.20
      #env:
        #DOCKER_HOST: tcp://0.0.0.0:2375
      ports:
        - 22
      #volumes:
      #  - my_docker_volume:/volume_mount
      #options: --cpus 1
    steps:
      - name: Set up SSH for Docker Context
        run: |
          # 创建 SSH 配置和密钥
          mkdir -p ~/.ssh
          echo "${{ vars.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "
          Host remote-docker
              HostName 47.109.69.39
              User root
              IdentityFile ~/.ssh/id_rsa
              StrictHostKeyChecking no
          " > ~/.ssh/config

          ssh-keyscan -H 47.109.69.39 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
          #export DOCKER_HOST=ssh://root@47.109.69.39

          # 创建 Docker Context
          docker context create remote --docker "host=ssh://remote-docker"
          docker context use remote
          cat ~/.ssh/id_rsa
          docker ps
  
      - name: Verify Docker Context
        run: |
          docker context ls
          docker images 